name: slashlock
version: '0.3'
summary: Easy to use file and folder encryptor
description: |
  Slashlock is a simple to use desktop application for encrypting and decrypting
  files and directories built in Python using Kivy.

grade: stable
confinement: strict

apps:
  slashlock:
    command: bin/wrapper

parts:
  kivy:
    plugin: nil
    stage-packages:
      - python3-kivy
      - libmtdev1

  wrapper:
    plugin: dump
    source: .
    organize:
      wrapper: bin/wrapper

  slashlockgui:
    plugin: dump
    source: https://github.com/wookalar/slashlockgui/archive/master.zip
    source-type: zip
    organize:
      slashlockgui/gui.py: bin/slashlockgui

