<ProcessingScreen@Screen>
    name: "processing_screen"

    AnchorLayout:
        id: processing_layout
        anchor_x: "center"
        anchor_y: "top"
        size_hint: (1, 1)
        padding: 20, 10

        Label:
            size_hint: (1, None)
            text: app.processing_status
            color: blue_back
            font_size: 16
            text_size: self.width, None
            height: self.texture_size[1]
            halign: 'left'