name: slashlock
version: '0.4'
summary: Easy to use file and folder encryptor
description: |
  Slashlock is a simple to use desktop application for encrypting and decrypting
  files and directories built in Python using Kivy.

grade: stable
confinement: strict

apps:
  slashlock:
    command: bin/wrapper

parts:
  kivy:
    plugin: python
    stage-packages:
      - cython3
      - python3-kivy
      - libmtdev1
      - python3-tk

  wrapper:
    plugin: dump
    source: snap/dump
    organize:
      wrapper: bin/wrapper
